// Extra rounds share the game's simulation clock, audio mixer and pause handling.
let bonusActive=false,bonusScore=0,bonusHits=0,bonusCombo=0,bonusStart=0,bonusEnd=0,
    bonusAttempt=-1,bonusStroke=-1e9,bonusMessage='',bonusMessageUntil=0,bonusIntroStart=0,
    sumoLastPhase='',sumoPushCycle=-1,sumoGood=-1e9,sumoFeedback='',sumoFeedbackUntil=0;
const BONUS_DURATION=12000;
let pushDown=false,pushStarted=-1,pushLastTick=0,pushEarned=0,pushCycle=-1,keepSaid=false;
// Longer warnings and release windows teach the same controls in Level 1.
const HOLD_MS=5600;
const RHYTHM_LEVELS=[
 {slowGap:320,fastGap:200,ready:2200,release:1600,minHold:700,fastHint:'ABOUT THREE TAPS A SECOND'},
 {slowGap:360,fastGap:180,ready:2000,release:1400,minHold:1000,fastHint:'THREE TO FOUR TAPS A SECOND'},
 {slowGap:400,fastGap:160,ready:1750,release:1200,minHold:1200,fastHint:'KEEP THE QUICK TAPS COMING'},
 {slowGap:440,fastGap:145,ready:1500,release:1000,minHold:1500,fastHint:'ABOUT FOUR TAPS A SECOND'},
 {slowGap:450,fastGap:140,ready:1400,release:950,minHold:1700,fastHint:'FOUR QUICK TAPS A SECOND'},
 {slowGap:460,fastGap:135,ready:1350,release:900,minHold:1800,fastHint:'FOUR QUICK TAPS A SECOND'}
];
function rhythmRules(){return RHYTHM_LEVELS[level];}
function rhythmPhases(){const r=rhythmRules();return SUMO_PHASES.map((p,i)=>({...p,end:i<2?p.end:i===2?6500+r.ready:i===3?6500+HOLD_MS+r.ready:6500+HOLD_MS+r.ready+r.release}));}
const SUMO_PHASES=[
  {key:'pace',end:4000,title:'SLOW TAPS',detail:'PACE YOURSELF · ABOUT TWO A SECOND',word:'SLOW',voice:'pace-it',color:'#76efff'},
  {key:'burst',end:6500,title:'FASTER! FASTER!',detail:'SHORT BURST · TAP QUICKLY!',word:'FASTER!',voice:'faster',color:'#fff24b'},
  {key:'ready',end:8000,title:'GET READY…',detail:'FINGER OFF · A BIG PUSH IS COMING',word:'READY',voice:'get-ready',color:'#ffb456'},
  {key:'hold',end:12000,title:'PUSH AND HOLD',detail:'KEEP THE BUTTON DOWN · NO TAPPING',word:'HOLD!',voice:'push-hold',color:'#ffcc68'},
  {key:'release',end:13000,title:'RELEASE NOW!',detail:'LET GO · +12 TIMING BONUS',word:'RELEASE!',voice:'release',color:'#bbff64'}
];
function sumoPhase(t){if(level===1||level===5||level===6)return signaturePhase(t);const elapsed=Math.max(0,t-roundStart),phases=rhythmPhases(),duration=phases[4].end,cycle=Math.floor(elapsed/duration),phaseTime=elapsed%duration;let begin=0;for(const phase of phases){if(phaseTime<phase.end)return {...phase,cycle,fraction:(phaseTime-begin)/(phase.end-begin),left:phase.end-phaseTime};begin=phase.end;}}
function resetPush(){resetSignature();pushDown=false;pushStarted=-1;pushLastTick=now();pushEarned=0;pushCycle=-1;keepSaid=false;}
function cancelPush(){stopFx('meter-hold');pushDown=false;pushStarted=-1;holding=false;}
function pressPush(){if(state!=='playing'||pauseReasons.size)return false;const phase=sumoPhase(now());if(phase.key!=='hold')return false;if(!pushDown){pushDown=true;pushStarted=now();pushLastTick=now();fx('meter-hold',.2,true);}return true;}
function releasePush(cancel=false){if(level===1||level===5||level===6){releaseSignature(cancel);return;}if(!pushDown)return;const t=now(),phase=sumoPhase(t),held=t-pushStarted;stopFx('meter-hold');pushDown=false;pushStarted=-1;if(cancel||pauseReasons.size||state!=='playing')return;if(phase.key==='release'&&held>=rhythmRules().minHold&&sumoPushCycle!==phase.cycle){sumoPushCycle=phase.cycle;perfectHits++;if(level===4)spaceVent=t;addSumoRelief(12,t);sumoFeedback='PERFECT RELEASE! +12 RELIEF';sumoFeedbackUntil=t+1400;fx('meter-release',.4);puff(400,740,-1);puff(800,740,1);}else{sumoFeedback=phase.key==='hold'?'TOO SOON! KEEP HOLDING UNTIL RELEASE.':'CATCH THE NEXT PUSH!';sumoFeedbackUntil=t+1200;}}
function rhythmGuide(title,detail,fraction,color){q('#rhythm-title').textContent=title;q('#rhythm-detail').textContent=detail;q('#rhythm-fill').style.width=clamp(fraction)*100+'%';q('#rhythm-guide').style.setProperty('--rhythm-color',color);}
function addSumoRelief(gain,t){taps=Math.min(LEVELS[level].target,taps+gain);const idx=Math.floor(progress()*4)-1;if(idx>awardIndex&&idx<3){awardIndex=idx;awardUntil=t+1600;q('#award').textContent='★ '+(level===3?['RICE BOWL SURVIVOR','ZEN OF THE THRONE','PORCELAIN GRAND CHAMPION']:AWARDS)[idx];}numbers();if(taps>=LEVELS[level].target)finish(t);}
function updateSumo(t){if(level===1||level===5||level===6){updateSignature(t);return;}const phase=sumoPhase(t);if(pushCycle!==phase.cycle){cancelPush();pushCycle=phase.cycle;pushEarned=0;keepSaid=false;}
  if(pushDown&&phase.key==='hold'){const amount=Math.min(14-pushEarned,Math.max(0,t-pushLastTick)/HOLD_MS*14);pushEarned+=amount;if(amount>0)addSumoRelief(amount,t);}pushLastTick=t;
  if(state!=='playing')return;
  const pressureSound=effects.get('meter-hold');if(pressureSound){pressureSound.audio.preservesPitch=false;pressureSound.audio.playbackRate=.85+progress()*.35+pushEarned/14*.15;pressureSound.audio.volume=.2*prefs.effects;}
  q('#rhythm-guide').hidden=false;rhythmGuide(phase.title,phase.key==='hold'?(pushDown?'KEEP HOLDING… '+Math.round(pushEarned/14*100)+'% PRESSURE':'PRESS AND KEEP IT DOWN'):phase.key==='burst'?rhythmRules().fastHint:phase.detail,phase.key==='hold'?pushEarned/14:phase.fraction,phase.color);
  const key=phase.cycle+phase.key;if(key!==sumoLastPhase&&t-roundStart>=voiceLengths.go){sumoLastPhase=key;fx('voice-'+(phase.key==='pace'&&phase.cycle%2?'steady':phase.voice),.85);q('#status').textContent=phase.title+'. '+phase.detail;}
  if(phase.key==='hold'&&pushDown&&phase.fraction*HOLD_MS>=voiceLengths['push-hold']+70&&t-pushStarted>=700&&phase.left>=voiceLengths['keep-holding']+50&&!keepSaid){keepSaid=true;fx('voice-keep-holding',.85);}
  q('#flush-word').textContent=phase.word;q('#flush-hint').textContent=phase.key==='hold'?'KEEP PRESSED':phase.key==='release'?'LET GO NOW':phase.key==='ready'?'FINGER OFF':phase.key==='pace'?'STEADY TAPS':'TAP QUICKLY';button.classList.toggle('ready',phase.key==='release');button.classList.toggle('charging',phase.key==='hold'||phase.key==='ready');button.classList.toggle('pushing',pushDown);
  setQuip(t<sumoFeedbackUntil?sumoFeedback:phase.key==='hold'?['HOLD THAT THOUGHT… AND THAT BUTTON!','THIS IS YOUR BIGGEST REP YET!','A ROYAL PUSH! KEEP HOLDING!','EVEN MOUNT FUJI IS HOLDING ITS BREATH…','SUIT PRESSURE RISING… HOLD YOUR ORBIT!','BATTEN DOWN THE HATCHES… KEEP HOLDING!'][level]:phase.key==='burst'?LEVELS[level].lines[Math.min(3,Math.floor(progress()*4))]:phase.key==='ready'?'GET READY TO PRESS AND HOLD!':phase.key==='release'?'LET GO NOW! YOU HAVE EARNED IT!':level===0?'FOLLOW THE COACH: SLOW, FAST, HOLD, RELEASE.':LEVELS[level].cause);
}
function tapSumo(t,auto){if(level===1||level===5||level===6){tapSignature(t,auto);return;}const phase=sumoPhase(t),gap=t-sumoGood;let gain=0;if(!auto)manualTaps++;lastTap=t;
  if(phase.key==='pace'&&gap>=rhythmRules().slowGap)gain=2.6;
  if(phase.key==='burst'&&gap>=rhythmRules().fastGap)gain=1.6;
  if(gain){sumoGood=t;fx('meter-tap',phase.key==='pace'?.22:.17);const meterSound=effects.get('meter-tap');if(meterSound){meterSound.audio.preservesPitch=false;meterSound.audio.playbackRate=.85+progress()*.55;}button.classList.add('hit');addSumoRelief(gain,t);}else if(!auto){sumoFeedback=phase.key==='pace'?'EASY! GIVE EACH TAP A LITTLE SPACE.':phase.key==='hold'?'PRESS AND KEEP IT DOWN!':phase.key==='release'?'LET GO OF THE BUTTON!':'FINGER OFF… GET READY!';sumoFeedbackUntil=t+650;}numbers();
}
function sumoScene(t){const p=progress(),plop=age('plop',t),motion=prefs.motion?0:1;
  for(const side of [-1,1]){const x=600+side*555;ctx.save();ctx.globalAlpha=.6;for(let i=0;i<3;i++){ctx.strokeStyle='#bafaff';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(x,(side<0?510:565)+i*13,45+i*13+Math.sin(t/300+i)*p*15*motion,8+i*3,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}
  for(let i=0;i<14;i++){const travel=motion?(t*.025+i*89)%1200:i*87;ctx.save();ctx.translate(travel,130+(i*71)%590+Math.sin(t/700+i)*20*motion);ctx.rotate(i+t/900*motion);ctx.fillStyle=i%2?'#ff92b8':'#ffdae6';ctx.beginPath();ctx.ellipse(0,0,7,3,0,0,Math.PI*2);ctx.fill();ctx.restore();}
  if(p>.55){for(let i=0;i<5;i++){const flight=motion?(t*.1+i*180)%1300:i*170,x=100+flight,y=150+i*18;line([[x-12,y],[x-6,y-6-Math.sin(t/100+i)*4*motion],[x,y],[x+6,y-6],[x+12,y]],'#18243b',3);}}
  if(p>.8){for(const side of [-1,1])line([[600+side*130,757],[600+side*170,790],[600+side*270,814],[600+side*330,859]],'#3e271b',5);}
  if(plop>=0){const u=clamp(plop/2.2),wave=Math.sin(u*Math.PI);for(const side of [-1,1]){ctx.save();ctx.globalAlpha=1-u;ctx.strokeStyle='#d2ffff';ctx.lineWidth=5;for(let ring=0;ring<3;ring++){ctx.beginPath();ctx.ellipse(600+side*555,565,90+u*180+ring*32,12+u*32+ring*5,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}if(plop<1.5&&t-lastWater>100){lastWater=t;puff(210,610,-1,'water');puff(990,610,1,'water');}if(plop<2.8){ctx.save();ctx.translate(190+plop*130,700-Math.sin(clamp(plop/2.8)*Math.PI)*440);ctx.rotate(plop*4*motion);roundRect(-36,-30,72,60,8,'#d99b39');line([[-25,-20],[-25,20]],'#ffcf73',5);line([[0,-20],[0,20]],'#704916',3);ctx.restore();}}
}
function introBonus(){bonusActive=true;bonusScore=0;bonusHits=bonusCombo=0;bonusAttempt=-1;bonusMessage='';bonusStroke=-1e9;bonusStart=now();bonusIntroStart=now();state='bonus-intro';holding=false;stopMusic();stopEffects();q('#plop').hidden=true;q('#award').hidden=true;q('#rhythm-guide').hidden=true;q('#result').hidden=false;q('#result-eyebrow').textContent='BONUS ROUND · 12 SECONDS';q('#result-title').textContent='PLUNGER PANIC!';q('#result-score').textContent='';q('#result-detail').textContent='Wait for the ring to reach the green target, then tap or press Space once. Let the plunger rise between pushes. Build a streak for extra points!';q('#best').textContent='BONUS POINTS ONLY · YOU ALWAYS CONTINUE';q('#next').textContent='GRAB THE PLUNGER';q('#next').disabled=false;q('#chapter').textContent='★ PLUNGER PANIC';q('#level-number').textContent='BONUS';q('#time').textContent='12.0';q('#score').textContent='0';q('#controls').hidden=true;setQuip('SAVE THE PLUMBING!');}
function startBonusCountdown(){state='bonus-countdown';countStart=now();countdownBeat=null;countdownLog=[];q('#result').hidden=true;q('#controls').hidden=false;button.disabled=true;q('#flush-word').textContent='PLUNGE';q('#flush-hint').textContent='ONE TAP ON GREEN';q('#percent').textContent='0 / 8';q('#fill').style.width='0%';q('#taps-label').textContent='0 GOOD PUSHES';q('.meter').setAttribute('aria-valuenow','0');button.classList.remove('ready','charging');announceCountdown(3);const a=tracks.bonusMusic;a.muted=true;a.play().then(()=>{if(state==='bonus-countdown'){a.pause();a.currentTime=0;}a.muted=muted;}).catch(()=>{a.muted=muted;});}
function bonusBeat(t){const elapsed=Math.max(0,t-bonusStart),index=Math.floor(elapsed/1000),phase=elapsed%1000;return {index,phase,ready:Math.abs(phase-750)<=180,perfect:Math.abs(phase-750)<=85};}
function bonusTap(){if(pauseReasons.size||state!=='bonus-playing')return;const t=now();if(t-bonusStart>=BONUS_DURATION){endBonus(t);return;}const beat=bonusBeat(t);if(bonusAttempt===beat.index)return;bonusAttempt=beat.index;bonusStroke=t;bonusSound('plunger',.34);
  if(beat.ready){bonusHits++;bonusCombo++;const gain=(beat.perfect?150:100)+Math.min(bonusCombo,10)*5;bonusScore+=gain;bonusMessage=(beat.perfect?'PERFECT!':'GOOD PUSH!')+' +'+gain+' · STREAK '+bonusCombo;}
  else{bonusCombo=0;bonusMessage=beat.phase<570?'TOO SOON! WAIT FOR GREEN.':'TOO LATE! CATCH THE NEXT RING.';}
  bonusMessageUntil=t+700;q('#score').textContent=bonusScore.toLocaleString('en-GB');q('#taps-label').textContent=bonusHits+' GOOD PUSHES';q('#percent').textContent=Math.min(8,bonusHits)+' / 8';q('#fill').style.width=clamp(bonusHits/8)*100+'%';q('.meter').setAttribute('aria-valuenow',String(Math.round(clamp(bonusHits/8)*100)));q('#status').textContent=bonusMessage;
}
function endBonus(t){state='bonus-ending';bonusEnd=t;holding=false;button.disabled=true;stopMusic();stopEffects();fx('splash',.55);q('#rhythm-guide').hidden=true;q('#flush-word').textContent='CLEAR!';q('#flush-hint').textContent='BONUS BANKED';setQuip(bonusHits>=8?'BLOCKAGE BUSTED! THE PIPES SALUTE YOU.':'EVERY GOOD PUSH COUNTS! BONUS BANKED.');}
function tickExpansion(t){if(lidsActive){tickLids(t);return;}if(scrubActive){tickScrub(t);return;}if(bonusActive){if(state==='bonus-countdown'){const elapsed=t-countStart;if(elapsed>=3000){state='bonus-playing';bonusStart=t;announceCountdown('GO');button.disabled=false;button.focus({preventScroll:true});playMusic('bonusMusic',true);}else announceCountdown(3-Math.floor(elapsed/1000));}
  if(state==='bonus-playing'){const elapsed=t-bonusStart;if(elapsed>=400)q('#countdown').hidden=true;const beat=bonusBeat(t),used=bonusAttempt===beat.index;button.classList.toggle('ready',beat.ready&&!used);button.classList.toggle('charging',!beat.ready||used);q('#flush-word').textContent=used?'RELEASE':beat.ready?'PUSH!':'WAIT';q('#flush-hint').textContent=used?'LET IT RISE':beat.ready?'TAP ONCE':'WATCH THE RING';setQuip(t<bonusMessageUntil?bonusMessage:used?'LET IT RISE… NEXT PUSH IS COMING':beat.ready?'PUSH! RIGHT ON THE GREEN RING!':'WAIT… LINE UP THE RINGS.');q('#time').textContent=(Math.max(0,BONUS_DURATION-elapsed)/1000).toFixed(1);if(elapsed>=BONUS_DURATION)endBonus(t);}
  if(state==='bonus-ending'&&t-bonusEnd>=1800){state='bonus-done';events.tally=t;fx('tally',.45,true,1800);q('#result').hidden=false;q('#result-title').textContent=bonusHits>=8?'PIPE DREAM!':'BONUS BANKED!';q('#result-eyebrow').textContent='PLUNGER PANIC COMPLETE';q('#result-score').textContent='0';q('#result-detail').textContent=bonusHits+' well-timed pushes. These points go into your final campaign tally.';q('#best').textContent=bonusHits>=8?'★ GOLDEN PLUNGER AWARDED':'THE KING IS WAITING. ONWARD!';q('#next').textContent='ON TO LEVEL 3';q('#next').disabled=true;}
  if(state==='bonus-done'){const u=clamp((t-events.tally)/1800);q('#result-score').textContent=Math.round(bonusScore*ease(u)).toLocaleString('en-GB');q('#next').disabled=u<1;if(u>=1)stopFx('tally');}
}else if(state!=='playing'&&state!=='countdown')q('#rhythm-guide').hidden=true;}
function drawBonus(t){ctx.drawImage(images.bathroom,0,0,1200,900);ctx.fillStyle='#031d39ad';ctx.fillRect(0,0,1200,900);const r=RECTS.props[0];ctx.drawImage(images.props,...r,315,140,570,700);
  const ending=['bonus-ending','bonus-done'].includes(state),drain=ending?clamp((t-bonusEnd)/1500):0,stroke=Math.max(0,1-(t-bonusStroke)/400),beat=bonusBeat(t);ctx.save();ctx.beginPath();ctx.ellipse(600,598,148,124,0,0,Math.PI*2);ctx.clip();ctx.fillStyle='#24c2dd';ctx.fillRect(430,465,340,290);ctx.translate(600,598);ctx.scale(1-drain*.75,1-drain*.75);ctx.rotate(prefs.motion?0:t/700);for(let i=0;i<4;i++){ctx.beginPath();for(let a=0;a<8;a+=.1){const radius=10+a*20;a?ctx.lineTo(Math.cos(a+i*Math.PI/2)*radius,Math.sin(a+i*Math.PI/2)*radius):ctx.moveTo(Math.cos(a+i*Math.PI/2)*radius,Math.sin(a+i*Math.PI/2)*radius);}ctx.strokeStyle='#8efaff';ctx.lineWidth=6;ctx.stroke();}ctx.restore();
  if(bonusHits<8){ctx.save();ctx.globalAlpha=(1-drain)*.9;for(let i=0;i<8-bonusHits;i++){const a=i*2.4,x=600+Math.cos(a)*90,y=615+Math.sin(a)*58;ctx.save();ctx.translate(x,y);ctx.rotate(a);roundRect(-16,-9,32,18,4,i%2?'#f4edca':'#ac6328','#5b3c2d',2);ctx.restore();}ctx.restore();}
  if(!ending){ctx.save();const active=state==='bonus-playing';ctx.translate(600,575);ctx.lineWidth=9;ctx.strokeStyle='#c3ff70';ctx.beginPath();ctx.ellipse(0,0,130,104,0,0,Math.PI*2);ctx.stroke();if(active){const radius=250-beat.phase*.16;ctx.strokeStyle=beat.ready?'#fff781':'#6cecff';ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(0,0,radius,radius*.8,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}
  ctx.save();ctx.translate(600,535+stroke*65-(ending?drain*400:0));ctx.rotate(prefs.motion?0:Math.sin(t/700)*.03);roundRect(-13,-245,26,230,10,'#e7b267','#263146',5);roundRect(-46,-254,92,28,12,'#efc97e','#263146',5);const compression=1-stroke*.3;ctx.scale(1+stroke*.13,compression);ctx.beginPath();ctx.moveTo(-90,35);ctx.bezierCurveTo(-75,-85,75,-85,90,35);ctx.closePath();ctx.fillStyle='#eb563a';ctx.strokeStyle='#351e2c';ctx.lineWidth=7;ctx.fill();ctx.stroke();roundRect(-101,24,202,26,12,'#b83332','#351e2c',5);line([[-48,-22],[-30,-39],[10,-45]],'#ffbd73',8);ctx.restore();
  if(state==='bonus-playing'){text('STREAK '+bonusCombo,970,360,32);text('8 PUSHES',230,420,26);text('TO CLEAR',230,455,26);}if(ending)text(bonusHits>=8?'UNBLOCKED!':'BONUS BANKED!',600,390,64,'#eaff7d');
}



