(()=>{'use strict';
const root=document.getElementById('rf-retro'),q=s=>root.querySelector(s),canvas=q('#game'),ctx=canvas.getContext('2d');
const ASSETS=__ASSETS__,RECTS=__RECTS__;
const LEVELS=[{name:'BANANA BANDIT',cause:'TOO MANY BANANAS · HELP HIM CLEAR IT',target:110,bg:'bathroom',hero:'banana',music:'music1',lines:['PEEL THE PRESSURE!','THOSE BANANAS ARE FIGHTING BACK!','SQUEEZE A LITTLE MORE!','ALMOST THERE!']},{name:'THE FINAL REP',cause:'SIX PROTEIN SHAKES · ZERO FIBRE',target:125,bg:'gym',hero:'bodybuilder',music:'music2',lines:['YOU GOT THIS, BIG GUY!','ONE MORE REP!','THIS IS ABOVE MY PAY GRADE!','EVERY LIFTER FOR THEMSELVES!']},{name:'ROYAL BLOCKAGE',cause:'TWELVE CHEESES · NO VEGETABLES',target:140,bg:'palace',hero:'king',music:'music3',lines:['YOUR PRUNE, YOUR MAJESTY!','A ROYAL EMERGENCY!','FETCH THE GOLDEN BRUSH!','HOLD ON TO YOUR CROWN!']},{name:'SUMO SHOWDOWN',cause:'FIVE BOWLS OF RICE · ONE TINY TOILET',target:150,bg:'bathhouse',hero:'sumo',music:'music4',lines:['PACE IT, BIG FELLA!','FASTER! FASTER!','HOLD… BUILD THE SUSPENSE!','PUSH! MAKE IT COUNT!']}];
const AWARDS=['GOLDEN TOILET BRUSH','BLEACH OF GLORY','EMERGENCY LAXATIVE'],DURATION=35000,images={},effects=new Map();
let prefs={music:.8,effects:1,motion:matchMedia('(prefers-reduced-motion: reduce)').matches,gentle:false,crt:true},records={classic:{levels:[0,0,0],campaign:0},gentle:{levels:[0,0,0],campaign:0}},unlocked=0;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
Object.assign(prefs,read('royal-flush-options',{}));for(const k of ['music','effects'])prefs[k]=Math.max(0,Math.min(1,Number(prefs[k])||0));const saved=read('royal-flush-records',null);if(saved?.classic?.levels&&saved?.gentle?.levels)records=saved;for(const mode of ['classic','gentle']){records[mode].levels=LEVELS.map((_,i)=>Number(records[mode].levels[i])||0);records[mode].expandedCampaign=Number(records[mode].expandedCampaign)||0;}unlocked=Math.max(0,Math.min(LEVELS.length-1,Number(read('royal-flush-unlocked',0))||0));
function save(){try{localStorage.setItem('royal-flush-options',JSON.stringify(prefs));localStorage.setItem('royal-flush-records',JSON.stringify(records));localStorage.setItem('royal-flush-unlocked',String(unlocked));}catch{}}
let state='loading',level=0,taps=0,manualTaps=0,campaign=LEVELS.map(()=>null),runMode='classic',roundStart=0,countStart=0,endStart=0,finalStart=0,scoreTotal=0,won=false,lastTap=-1e9,perfectIndex=0,perfectStart=-1,perfectUntil=0,perfectHits=0,awardIndex=-1,awardUntil=0,events={},particles=[],lastSteam=0,lastWater=0,lastFrame=0,holding=false,holdAccumulator=0,muted=false,music=null,pausedTotal=0,pauseStart=0,pauseReasons=new Set(),tileVariant=-1,mouseDirection=1,tallyStarted=false,finalTally=-1,lastQuip='',raf=0,countdownBeat=null,countdownLog=[],gymMetrics={};
const now=()=> (pauseReasons.size?pauseStart:performance.now())-pausedTotal,clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n)),ease=t=>1-Math.pow(1-clamp(t),3),progress=()=>Math.min(1,Math.pow(taps/LEVELS[level].target,.85));
let voiceUntil=0;const voiceLengths={"pace-it": 1715, "steady": 2155, "faster": 1935, "get-ready": 975, "push-hold": 3075, "keep-holding": 2255, "release": 1075, "relief": 2585, "three": 775, "two": 735, "one": 735, "go": 1225};
function updateVolumes(){if(music)music.volume=.48*prefs.music*(prefs.effects>0&&now()<voiceUntil?.80:1);for(const item of effects.values())item.audio.volume=item.gain*prefs.effects;}
function makeAudio(name){const a=new Audio(ASSETS[name]);a.preload='auto';a.muted=muted;return a;}
const tracks={};for(const n of ['menuMusic','music1','music2','music3','music4','bonusMusic'])tracks[n]=makeAudio(n);
function playMusic(name,restart=false){const next=tracks[name];if(music&&music!==next)music.pause();music=next;if(restart)music.currentTime=0;music.loop=['menuMusic','music4','bonusMusic'].includes(name);music.volume=.48*prefs.music;music.muted=muted;if(!pauseReasons.size)music.play().then(()=>{q('#audio-notice').textContent='TAP / SPACE TO FLUSH';}).catch(error=>{if(error.name==='NotAllowedError')q('#audio-notice').textContent='CLICK ANYWHERE TO ENABLE SOUND';});}
function stopMusic(){if(music)music.pause();music=null;}
function fx(name,gain=.55,loop=false,duration=0){if(!ASSETS[name])return;if(name.startsWith('voice-')){gain*=.62;for(const [key,e]of effects)if(key.startsWith('voice-')){e.audio.pause();e.stop=0;e.resume=false;}voiceUntil=now()+(voiceLengths[name.slice(6)]||1500);}let item=effects.get(name);if(!item){item={audio:makeAudio(name),gain,stop:0};effects.set(name,item);}item.audio.pause();item.audio.currentTime=0;item.gain=gain;item.audio.volume=gain*prefs.effects;item.audio.muted=muted;item.audio.loop=loop;item.stop=duration?now()+duration:0;if(!pauseReasons.size)item.audio.play().catch(()=>{});}
function stopFx(name){const e=effects.get(name);if(e){e.audio.pause();e.stop=0;e.resume=false;}}
function stopEffects(){voiceUntil=0;effects.forEach(e=>{e.audio.pause();e.stop=0;e.resume=false;});}

const countdownClips={3:'voice-three',2:'voice-two',1:'voice-one',GO:'voice-go'};
function announceCountdown(beat){
  if(countdownBeat===beat)return;
  countdownBeat=beat;countdownLog.push({beat,at:now()});
  for(const name of Object.values(countdownClips))stopFx(name);
  q('#countdown').textContent=String(beat);q('#countdown').hidden=false;
  q('#countdown').classList.remove('arcade-beat');
  if(!prefs.motion){void q('#countdown').offsetWidth;q('#countdown').classList.add('arcade-beat');}
  fx(countdownClips[beat],.85);
}

function unlockAudio(){if(bonusActive){if(music?.paused&&!pauseReasons.size)music.play().catch(()=>{});return;}if(state==='menu')playMusic('menuMusic');else if(state==='playing'&&music?.paused&&!pauseReasons.size)playMusic(LEVELS[level].music);}
root.addEventListener('pointerdown',unlockAudio,{capture:true});root.addEventListener('keydown',unlockAudio,{capture:true});
function pause(reason){if(!pauseReasons.size){pauseStart=performance.now();if(music)music.pause();effects.forEach(e=>{e.resume=!e.audio.paused;e.audio.pause();});}pauseReasons.add(reason);spaceDown=false;inputPointer=null;cancelPush();holding=false;}
function resume(reason){if(!pauseReasons.has(reason))return;pauseReasons.delete(reason);if(!pauseReasons.size){pausedTotal+=performance.now()-pauseStart;if(music)music.play().catch(()=>{});effects.forEach(e=>{if(e.resume){e.resume=false;e.audio.play().catch(()=>{});}});}}
document.addEventListener('visibilitychange',()=>document.hidden?pause('hidden'):resume('hidden'));
q('#sound-button').onclick=()=>{muted=!muted;Object.values(tracks).forEach(a=>a.muted=muted);effects.forEach(e=>e.audio.muted=muted);q('#sound-button').textContent=muted?'SOUND OFF':'SOUND ON';q('#sound-button').setAttribute('aria-pressed',String(!muted));if(!muted)unlockAudio();};
q('#options-button').onclick=()=>{pause('options');q('#settings').showModal();};q('#settings-done').onclick=()=>q('#settings').close();q('#settings').addEventListener('close',()=>resume('options'));
for(const [id,key]of [['music-volume','music'],['effects-volume','effects']]){q('#'+id).value=prefs[key];q('#'+id).oninput=e=>{prefs[key]=Number(e.target.value);updateVolumes();save();};}
for(const [id,key]of [['reduce-motion','motion'],['gentle','gentle'],['crt','crt']]){q('#'+id).checked=!!prefs[key];q('#'+id).onchange=e=>{prefs[key]=e.target.checked;q('#scanlines').hidden=!prefs.crt;save();};}q('#scanlines').hidden=!prefs.crt;
function setQuip(text){if(text!==lastQuip){lastQuip=text;q('#quip').textContent=text;}}
function cards(){q('#challenges').replaceChildren();LEVELS.forEach((l,i)=>{const b=document.createElement('button');b.className='challenge';b.setAttribute('aria-pressed',String(i===level));b.setAttribute('aria-label',l.name+(i>unlocked?', locked':''));b.innerHTML='<span class="num">LEVEL '+(i+1)+'</span><span class="stars">'+'★'.repeat(i+1)+'</span><span class="lock">'+(i>unlocked?'LOCKED':'')+'</span><canvas class="portrait" width="180" height="130"></canvas><span class="name">'+l.name+'</span><span class="tag">'+(['BATHROOM','GYM','PALACE','MT FUJI'][i])+'</span>';const c=b.querySelector('canvas').getContext('2d'),r=RECTS[l.hero][0];const crop=Math.min(r[2],r[3]*.49);c.drawImage(images[l.hero],r[0]+(r[2]-crop)/2,r[1],crop,crop,25,0,130,130);b.onclick=()=>{if(i>unlocked){q('#menu-note').textContent='CLEAR LEVEL '+i+' TO UNLOCK THIS CHALLENGE';return;}level=i;cards();};q('#challenges').append(b);});q('#menu-note').textContent=level===0?'FOUR LEVELS + PLUNGER BONUS · ONE ROYAL SCORE':'PRACTICE RUN · START AT LEVEL 1 FOR A CAMPAIGN TOTAL';}
function menu(){cancelPush();bonusActive=false;q('#rhythm-guide').hidden=true;state='menu';holding=false;stopEffects();q('#result').hidden=true;q('#finale').hidden=true;q('#countdown').hidden=true;q('#plop').hidden=true;q('#award').hidden=true;q('#hud').hidden=true;q('#controls').hidden=true;q('#chapter').hidden=true;q('#quip').hidden=true;q('#menu').hidden=false;q('#menu-deck').hidden=false;q('#stage').className='stage menu-stage';cards();playMusic('menuMusic');}
function newCampaign(){bonusScore=0;campaign=LEVELS.map(()=>null);level=0;runMode=prefs.gentle?'gentle':'classic';startRound();}
function startRound(){resetPush();button.classList.remove('pushing');bonusActive=false;sumoLastPhase='';sumoPushCycle=-1;sumoGood=-1e9;sumoFeedback='';sumoFeedbackUntil=0;q('#rhythm-guide').hidden=false;rhythmGuide('FOLLOW THE COACH','SLOW → FAST → PUSH & HOLD → RELEASE',0,'#76efff');stopMusic();stopEffects();state='countdown';taps=manualTaps=0;scoreTotal=0;won=false;particles=[];events={};lastTap=-1e9;perfectIndex=perfectHits=0;perfectStart=-1;perfectUntil=0;awardIndex=-1;awardUntil=0;holding=false;holdAccumulator=0;lastSteam=lastWater=0;tallyStarted=false;mouseDirection=Math.random()<.5?-1:1;countStart=now();countdownBeat=null;countdownLog=[];gymMetrics={};q('#menu').hidden=true;q('#menu-deck').hidden=true;q('#result').hidden=true;q('#finale').hidden=true;q('#plop').hidden=true;q('#award').hidden=true;q('#hud').hidden=false;q('#controls').hidden=false;q('#chapter').hidden=false;q('#quip').hidden=false;q('#stage').className='stage';q('#chapter').textContent='★ '+LEVELS[level].name;q('#level-number').textContent=(level+1)+'/'+LEVELS.length;q('#countdown').hidden=false;q('#countdown').textContent='3';q('#rf-flush').disabled=true;q('#flush-word').textContent='FLUSH!';q('#flush-hint').textContent='TAP / SPACE';button.classList.remove('ready','charging');q('#time').textContent='35.0';q('#mode-label').textContent=runMode==='gentle'?'GENTLE PLAY · HOLD TO TAP':'CLASSIC ARCADE';q('#gentle').disabled=true;setQuip(LEVELS[level].cause);numbers();q('#status').textContent=LEVELS[level].name+'. Get ready.';q('#plop').classList.toggle('gym-pop',level===1);announceCountdown(3);
// Priming this track on the Start gesture keeps later playback compatible with browser audio policies.
const a=tracks[LEVELS[level].music];a.muted=true;a.play().then(()=>{if(state==='countdown'){a.pause();a.currentTime=0;}a.muted=muted;}).catch(()=>{a.muted=muted;});}
q('#start').onclick=()=>{bonusScore=0;campaign=LEVELS.map(()=>null);runMode=prefs.gentle?'gentle':'classic';startRound();};q('#home').onclick=()=>{q('#gentle').disabled=false;menu();};q('#final-home').onclick=()=>{q('#gentle').disabled=false;menu();};q('#new-run').onclick=newCampaign;
q('#next').onclick=()=>{if(bonusActive){if(state==='bonus-intro')startBonusCountdown();else if(state==='bonus-done'){bonusActive=false;level=2;startRound();}return;}if(won&&level===LEVELS.length-1){if(campaign.every(Boolean))beginFinale();else{q('#gentle').disabled=false;menu();}}else if(won&&level===1){introBonus();}else{if(won)level++;startRound();}};
function numbers(){const p=progress();q('#percent').textContent=Math.floor(p*100)+'%';q('#fill').style.width=p*100+'%';q('.meter').setAttribute('aria-valuenow',String(Math.floor(p*100)));q('#score').textContent=Math.min(2999,Math.floor(p*3000)).toLocaleString('en-GB');q('#taps-label').textContent=manualTaps+' TAPS';}
function tap(auto=false){if(state==='bonus-playing'){bonusTap();return;}if(state!=='playing'||pauseReasons.size)return;const t=now();if(t-roundStart>=DURATION){finish(t);return;}tapSumo(t,auto);}
const button=q('#rf-flush');let inputPointer=null,spaceDown=false;
button.addEventListener('pointerdown',e=>{if(e.button!==0||inputPointer!==null||spaceDown)return;e.preventDefault();button.focus({preventScroll:true});if(!['playing','bonus-playing'].includes(state))return;inputPointer=e.pointerId;button.setPointerCapture(e.pointerId);if(!pressPush())tap();holding=runMode==='gentle';holdAccumulator=0;});
button.addEventListener('pointerup',e=>{if(inputPointer!==e.pointerId)return;inputPointer=null;releasePush();holding=false;});
for(const event of ['pointercancel','lostpointercapture'])button.addEventListener(event,e=>{if(inputPointer===e.pointerId){inputPointer=null;releasePush(true);holding=false;}});
button.addEventListener('click',e=>{if(e.detail===0&&!spaceDown)tap();});
root.addEventListener('keydown',e=>{if(e.code==='Space'&&['playing','bonus-playing'].includes(state)&&!q('#settings').open&&![q('#sound-button'),q('#options-button')].includes(e.target)){e.preventDefault();if(!e.repeat&&!spaceDown&&inputPointer===null){spaceDown=true;if(!pressPush())tap();holding=runMode==='gentle';holdAccumulator=0;}}});
root.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();if(spaceDown){spaceDown=false;releasePush();holding=false;}}});
window.addEventListener('blur',()=>{spaceDown=false;inputPointer=null;cancelPush();});
function finish(t){if(state!=='playing')return;numbers();sequence(t);state='ending';cancelPush();button.classList.remove('pushing');endStart=t;won=taps>=LEVELS[level].target;scoreTotal=won?3000+Math.floor(clamp((DURATION-(t-roundStart))/1000,0,35)*100):Math.min(2999,Math.floor(progress()*3000));holding=false;stopMusic();stopEffects();q('#rf-flush').disabled=true;q('#flush-word').textContent=won?'AHH!':'TIME';q('#flush-hint').textContent='ROUND COMPLETE';button.classList.remove('ready','charging');q('#score').textContent=scoreTotal.toLocaleString('en-GB');if(won){campaign[level]={score:scoreTotal};unlocked=Math.max(unlocked,Math.min(LEVELS.length-1,level+1));records[runMode].levels[level]=Math.max(records[runMode].levels[level],scoreTotal);save();}setQuip(won?'BRACE YOURSELVES…':'SO CLOSE! ONE MORE TRY.');q('#award').hidden=true;q('#status').textContent=won?'Level complete.':'Time is up.';}
function results(t){state='done';tallyStarted=true;fx('tally',.45,true,2400);events.tally=t;q('#result').hidden=false;q('#result-title').textContent=won?'ROYAL RELIEF!':'ALMOST THERE!';q('#result-eyebrow').textContent=LEVELS[level].name;q('#result-score').textContent='0';q('#result-detail').textContent=won?'3,000 clear bonus + '+(scoreTotal-3000).toLocaleString('en-GB')+' speed bonus.':'Just '+(3000-scoreTotal).toLocaleString('en-GB')+' more points in one attempt to clear this level.';q('#next').textContent=won?(level<LEVELS.length-1?(level===1?'PLUNGER BONUS':'NEXT LEVEL'):campaign.every(Boolean)?'FINAL TALLY':'BACK TO MENU'):'TRY AGAIN';q('#next').disabled=true;q('#best').textContent=runMode.toUpperCase()+' BEST '+records[runMode].levels[level].toLocaleString('en-GB')+' · '+perfectHits+' PERFECT RELEASES';q('#status').textContent=q('#result-detail').textContent;}
function beginFinale(){if(!campaign.every(Boolean))return;stopEffects();state='finale';finalStart=now();finalTally=-1;q('#result').hidden=true;q('#plop').hidden=true;q('#finale').hidden=false;q('#controls').hidden=true;q('#hud').hidden=true;q('#chapter').hidden=true;q('#quip').hidden=true;q('#stage').className='stage finale-stage';q('#rhythm-guide').hidden=true;q('#final-rows').innerHTML=LEVELS.map((l,i)=>'<div>'+l.name+'<b id="final-row-'+i+'">0</b></div>').join('')+'<div>PLUNGER BONUS<b id="final-bonus">0</b></div>';const total=campaign.reduce((s,x)=>s+x.score,bonusScore);records[runMode].expandedCampaign=Math.max(records[runMode].expandedCampaign,total);save();q('#campaign-best').textContent=runMode.toUpperCase()+' BEST '+records[runMode].expandedCampaign.toLocaleString('en-GB');q('#new-run').disabled=true;}
function tickFinale(t){const elapsed=t-finalStart;let total=0;campaign.forEach((entry,i)=>{const n=Math.round(entry.score*clamp((elapsed-i*2000)/1600));total+=n;q('#final-row-'+i).textContent=n.toLocaleString('en-GB');});const extra=Math.round(bonusScore*clamp((elapsed-LEVELS.length*2000)/1600));total+=extra;q('#final-bonus').textContent=extra.toLocaleString('en-GB');const index=Math.floor(elapsed/2000);if(index<LEVELS.length+1&&index!==finalTally){finalTally=index;fx('tally',.45,true,1600);}q('#final-total').textContent=total.toLocaleString('en-GB');q('#needle').style.transform='rotate('+(-90+clamp(total/27000)*180)+'deg)';q('.dial').style.setProperty('--fill-angle',clamp(total/27000)*180+'deg');q('#rank').textContent=total>=23000?'PORCELAIN LEGEND':total>=19500?'ROYAL FLUSH':total>=16000?'PLUMBING MENACE':'RESPECTABLE RELIEF';if(elapsed>=(LEVELS.length+1)*2000&&q('#new-run').disabled){q('#new-run').disabled=false;fx('royal-fanfare',.6);q('#status').textContent='Campaign total '+total+'. '+q('#rank').textContent;}}
function trigger(name,threshold,t,sound){if(progress()>=threshold&&events[name]===undefined){events[name]=t;if(sound)fx(sound);return true;}return false;}
function age(name,t){return events[name]===undefined?-1:(t-events[name])/1000;}
function sequence(t){if(!['playing','ending','done'].includes(state))return;trigger('steam',.2,t,state==='playing'?'steam':null);if(level===0){trigger('water',.3,t,'water');trigger('holder',.42,t,'holder');if(age('holder',t)>.55&&events.paper===undefined){events.paper=t;fx('paper');}if(trigger('tiles',.55,t)){tileVariant=(tileVariant+1+Math.floor(Math.random()*3))%4;fx('tile'+(tileVariant+1));}if(age('tiles',t)>.4)trigger('cupboard',.62,t);if(age('cupboard',t)>.45)trigger('mouse',.68,t);trigger('cracks',.8,t);trigger('sign',.9,t);for(let i=1;i<4;i++)if(age('tiles',t)>i*.38&&events['tile-sfx'+i]===undefined){events['tile-sfx'+i]=t;tileVariant=(tileVariant+1+Math.floor(Math.random()*3))%4;fx('tile'+(tileVariant+1),.4);}}
if(level===1){trigger('rattle',.18,t,'gym-rattle');trigger('lower',.58,t,'gym-lower');trigger('blast',.45,t,'gym-blast');trigger('trainer',.58,t,'gym-footsteps');trigger('lifter',.7,t,'gym-barbell');if(trigger('runner',.82,t))fx('gym-treadmill',.3,true);trigger('sign',.9,t,'gym-sign');}
if(level===2){trigger('fanfare',.08,t,'royal-fanfare');trigger('tray',.18,t,'royal-tray');trigger('gust',.35,t,'royal-gust');trigger('chandelier',.5,t,'royal-chandelier');trigger('guards',.68,t,'royal-guards');trigger('armour',.82,t,'royal-armour');trigger('crown',.94,t);}}
function puff(x,y,dir,kind='steam'){const count=prefs.motion?1:kind==='water'?4:kind==='steam'?2:3;for(let i=0;i<count;i++)particles.push({x,y,vx:dir*(80+Math.random()*140),vy:kind==='water'?-220-Math.random()*230:-35-Math.random()*100,age:0,life:kind==='water'?1.7:.7+Math.random()*.4,r:kind==='water'?5+Math.random()*9:8+Math.random()*12,kind});if(particles.length>180)particles.splice(0,particles.length-180);}
function drawParticle(p){ctx.save();ctx.globalAlpha=Math.max(0,1-p.age/p.life);ctx.translate(p.x,p.y);ctx.lineWidth=3;ctx.strokeStyle='#16354b';const r=p.r;if(p.kind==='steam'){ctx.scale(1+p.age,1+p.age);ctx.fillStyle='#f5f7e8';ctx.beginPath();ctx.moveTo(-r,r*.4);ctx.bezierCurveTo(-r*2,r*.4,-r*2,-r*.7,-r,-r*.7);ctx.bezierCurveTo(-r,-r*1.8,r*.6,-r*1.8,r*.8,-r*.7);ctx.bezierCurveTo(r*2,-r,r*2,r*.6,r,r*.6);ctx.bezierCurveTo(r*.6,r*1.2,-r*.6,r*1.2,-r,r*.4);ctx.closePath();}else{ctx.rotate(p.vx>0?.5:-.5);ctx.fillStyle='#67edff';ctx.beginPath();ctx.moveTo(0,-r);ctx.quadraticCurveTo(r,r,0,r);ctx.quadraticCurveTo(-r,r,0,-r);}ctx.fill();ctx.stroke();ctx.restore();}
function sprite(name,index,x,y,h,rotation=0,flip=1){const r=RECTS[name][index],w=h*r[2]/r[3];ctx.save();ctx.translate(x,y);ctx.rotate(rotation);ctx.scale(flip,1);ctx.drawImage(images[name],...r,-w/2,-h,w,h);ctx.restore();return w;}
function roundRect(x,y,w,h,r,fill,stroke='#0a1b31',line=4){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(line){ctx.strokeStyle=stroke;ctx.lineWidth=line;ctx.stroke();}}
function text(word,x,y,size=28,color='#fff243'){ctx.font='900 '+size+'px Arial';ctx.textAlign='center';ctx.lineWidth=5;ctx.strokeStyle='#10182b';ctx.strokeText(word,x,y);ctx.fillStyle=color;ctx.fillText(word,x,y);}
function line(points,color,width){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineJoin='round';ctx.stroke();}
function tilePatch(x,y,w,h){ctx.drawImage(images.bathroom,480,260,90,95,x,y,w,h);}
function bathroom(t){const bg=images.bathroom;
const waterAge=age('water',t);if(waterAge>=0){ctx.save();ctx.globalAlpha=.6;ctx.fillStyle='#38e2ee';ctx.beginPath();ctx.ellipse(905,693,125*ease(waterAge/2),26,0,0,Math.PI*2);ctx.fill();ctx.restore();const sway=prefs.motion?0:Math.sin(t/95)*12;line([[906,427],[905,385],[897+sway,339],[875+sway,307]],'#102f4c',14);line([[906,427],[905,385],[897+sway,339],[875+sway,307]],'#49e9ff',8);line([[904,386],[940+sway,353],[964+sway,355]],'#67f8ff',5);if(t-lastWater>90){lastWater=t;puff(900,367,-1,'water');puff(910,367,1,'water');}}
const holderAge=age('holder',t);if(holderAge>=0){tilePatch(163,386,167,171);const y=420+Math.min(240,holderAge*holderAge*450);ctx.save();ctx.translate(228,y);ctx.rotate(prefs.motion?0:Math.min(2.4,holderAge*3));ctx.drawImage(bg,180,386,120,165,-60,-50,120,165);ctx.restore();const paperAge=age('paper',t);if(paperAge>=0){const len=clamp(paperAge/2)*470;const pts=[];for(let x=0;x<=len;x+=15)pts.push([210+x,735+Math.sin(x/37)*14]);line(pts,'#10233c',29);line(pts,'#fff5d4',22);for(let x=40;x<len;x+=45)line([[210+x,723+Math.sin(x/37)*14],[210+x,747+Math.sin(x/37)*14]],'#cebba1',2);ctx.save();ctx.translate(220+len,733);ctx.rotate(prefs.motion?0:paperAge*4);roundRect(-24,-26,48,52,8,'#fff6db');ctx.fillStyle='#685242';ctx.beginPath();ctx.ellipse(0,0,10,17,0,0,Math.PI*2);ctx.fill();ctx.restore();}}
const tileAge=age('tiles',t);if(tileAge>=0){const coords=[[425,125],[772,234],[396,370],[1080,258],[740,112],[320,510],[925,190]];coords.forEach(([x,y],i)=>{const a=tileAge-i*.24;if(a<0)return;roundRect(x,y,69,76,1,'#33545a','#162d35',3);const drop=Math.min(755-y,a*a*330),rot=prefs.motion?0:a*(i%2?1:-1);ctx.save();ctx.translate(x+35+(i%2?1:-1)*Math.min(25,a*20),y+38+drop);ctx.rotate(rot);roundRect(-34,-38,68,76,3,'#8cdbcf','#173944',3);line([[-27,-29],[22,-29]],'#cefff1',3);ctx.restore();});}
const cupboardAge=age('cupboard',t);if(cupboardAge>=0){roundRect(125,157,224,185,3,'#142634','#0d1e2c',5);const doorW=110*(1-.85*ease(cupboardAge));ctx.drawImage(bg,127,158,109,184,125,157,doorW,184);ctx.drawImage(bg,237,158,110,184,349-doorW,157,doorW,184);}
const m=age('mouse',t);if(m>=0&&m<4.4){let x=236,y=335,h=90,rot=0;if(m>1.1){const u=clamp((m-1.1)/1.2);x=236+mouseDirection*270*u;y=335+420*u-Math.sin(u*Math.PI)*230;rot=prefs.motion?0:Math.sin(u*Math.PI)*.2;if(m>2.3){x=236+mouseDirection*(270+(m-2.3)*560);y=755+(prefs.motion?0:Math.abs(Math.sin(m*24))*9);}}else x+=prefs.motion?0:Math.sin(t/35)*3;sprite('cast',0,x,y,h,rot,mouseDirection===1?-1:1);if(m<1.2)text('!',x+35,y-90,40,'#ffec35');}
const crackAge=age('cracks',t);if(crackAge>=0){const n=clamp(crackAge/1.5);for(const side of [-1,1]){const p=[[600+side*60,752],[600+side*120,772],[600+side*148,803],[600+side*220,818],[600+side*250,862],[600+side*360,882]];line(p.slice(0,Math.max(2,Math.ceil(n*p.length))),'#12262f',7);line([[600+side*148,803],[600+side*113,840],[600+side*150,878]],'#1b3740',4);}}
const signAge=age('sign',t);ctx.save();ctx.translate(1105,signAge>=0?Math.min(714,210+signAge*signAge*300):210);ctx.rotate(signAge>=0&&!prefs.motion?Math.min(1,signAge):.07);roundRect(-62,-36,124,72,3,'#fff1c3','#183041',3);text(signAge>=0?'PANIC':'KEEP',0,-3,22);text(signAge>=0?'NOW!':'CALM',0,22,22);ctx.restore();}
function barbell(x,y,rotation=0){ctx.save();ctx.translate(x,y);ctx.rotate(rotation);line([[-97,0],[97,0]],'#0a1322',13);line([[-97,0],[97,0]],'#a4c5db',7);for(const side of [-1,1]){roundRect(side*72-13,-32,26,64,5,'#322959');roundRect(side*88-8,-25,16,50,4,'#6e69a4');}ctx.restore();}
__GYM_ANIMATION__
__EXPANSION__
function palace(t){const guard=age('guards',t),tray=age('tray',t),gust=age('gust',t),armour=age('armour',t),ch=age('chandelier',t),plopAge=age('plop',t);sprite('props',2,600,200,205,prefs.motion?0:(ch>=0?.19:.025)*Math.sin(t/(ch>=0?170:1000)));for(const side of [-1,1]){const x=600+side*(420+(guard>=0?guard*500:0));sprite('cast',4,x,735,290,(guard>=0?side*.16:0),side===1?-1:1);}
const flee=gust>=0?Math.max(0,gust-1.4):0;if(flee<2){const x=295-flee*420,royalBow=plopAge>=0?Math.sin(Math.min(1,plopAge)*Math.PI/2)*.35:0;sprite('cast',5,x,782,258,-royalBow);if(tray>=0&&tray<1.5)text(tray<.7?'PRUNES?':'LAXATIVE?',x,505,23);}if(gust>=0&&gust<2){const a=gust;ctx.save();ctx.translate(335+a*235,550-a*270+a*a*110);ctx.rotate(a*6);ctx.fillStyle='#e2e8f2';ctx.strokeStyle='#15233b';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,0,40,9,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}
sprite('cast',6,910,765,220,plopAge>=0?-.2:Math.sin(t/500)*.015,-1);if(armour<0)sprite('cast',7,1085,655,230);else{const a=clamp(armour/1.3);ctx.save();ctx.translate(1085,655);ctx.rotate(a*1.5);sprite('cast',7,0,0,230);ctx.restore();}if(guard>=0&&guard<1.5){ctx.save();ctx.translate(980+guard*100,600+guard*guard*80);ctx.rotate(guard*5);roundRect(-24,-25,48,50,15,'#c7dfec');ctx.restore();}}
function drawHero(t){const p=progress(),active=state==='playing',imp=active?Math.max(0,1-(t-lastTap)/240):0,name=LEVELS[level].hero,frame=won&&['ending','done'].includes(state)?0:pushDown?(pushEarned>8?2:1):p<.25?0:p<.65?1:2,r=RECTS[name][frame];const h=level===1?588:level===2?622:615,w=h*r[2]/r[3],x=600,y=level===1?187:level===2?162:166,motion=prefs.motion?0:1;ctx.fillStyle='#09223866';ctx.beginPath();ctx.ellipse(x,790,w*.53,23,0,0,Math.PI*2);ctx.fill();const crownAge=age('crown',t);const cropCrown=level===2&&crownAge>=0,bulk=level===1?gymBulk(t):{inflation:0,deflation:0};ctx.save();ctx.globalAlpha=1-bulk.deflation;
for(let sy=0;sy<r[3];sy+=8){const sh=Math.min(8,r[3]-sy),v=sy/r[3],v2=(sy+sh)/r[3];if(cropCrown&&v<.185)continue;const dy=z=>y+z*h+Math.sin(z*Math.PI)*(Math.sin(t/430)*2-imp*10)*motion-Math.exp(-Math.pow((z-.6)/.11,2))*Math.max(0,Math.sin(t/95))*p*5*motion;const dx=active&&frame===2?Math.sin(t/33)*1.6*Math.sin(v*Math.PI)*motion:0;const top=dy(v),bottom=dy(v2),muscleEnvelope=Math.exp(-Math.pow((v-.43)/.19,4)),stretch=1+imp*.02*Math.sin(v*Math.PI)*motion+(bulk.inflation-(bulk.inflation+.42)*bulk.deflation)*muscleEnvelope;if(v>.87&&active&&!prefs.motion){for(let side=0;side<2;side++){const heel=Math.max(0,Math.sin(t/95+side*Math.PI))*p*4;ctx.drawImage(images[name],r[0]+side*r[2]/2,r[1]+sy,r[2]/2,sh,x-w*stretch/2+side*w*stretch/2+dx,top-heel,w*stretch/2,bottom-top+.6);}}else ctx.drawImage(images[name],r[0],r[1]+sy,r[2],sh,x-w*stretch/2+dx,top,w*stretch,bottom-top+.6);}
ctx.restore();if(level===1&&bulk.deflation>0){ctx.save();ctx.globalAlpha=bulk.deflation;sprite('deflated',0,600,y+h,h);ctx.restore();}
if(cropCrown){const launch=won?Math.max(0,age('plop',t)):0;const rise=launch>0?Math.sin(clamp(launch/1.7)*Math.PI)*120:0;sprite('props',3,600+Math.sin(t/80)*Math.min(crownAge,1)*3,280-rise,115,launch>1.7?.2:Math.sin(t/100)*.06);}
if(active&&frame>0&&t-lastSteam>(frame===2?270:550)){lastSteam=t;const ears=level===1?114:level===2?126:140,ey=level===2?380:level===1?330:365;puff(600-ears,ey,-1);puff(600+ears,ey,1);if(frame===2&&manualTaps%3===0)puff(600,ey+35,Math.random()<.5?-1:1);}
if(active&&imp>.1&&!prefs.motion)for(const side of [-1,1])line([[600+side*(w*.55),480],[600+side*(w*.6),464],[600+side*(w*.57),501]],'#fff34f',6);
}
function drawMenu(t){ctx.drawImage(images.bathroom,0,0,1200,900);ctx.fillStyle='#2ab6c026';ctx.fillRect(0,0,1200,900);const r=RECTS.props[0];ctx.drawImage(images.props,...r,389,151,422,545);ctx.save();ctx.beginPath();ctx.ellipse(599,510,112,105,0,0,Math.PI*2);ctx.clip();ctx.translate(599,510);ctx.scale(1,.95);ctx.rotate(prefs.motion?0:t/900);for(let j=0;j<4;j++){ctx.beginPath();for(let a=0;a<Math.PI*3;a+=.08){const radius=8+a*12,x=Math.cos(a+j*Math.PI/2)*radius,y=Math.sin(a+j*Math.PI/2)*radius;a===0?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.strokeStyle=j%2?'#8dfaff':'#0b96d4';ctx.lineWidth=j%2?6:12;ctx.stroke();}ctx.restore();const a=prefs.motion?-.8:t/1600;sprite('props',1,599+Math.cos(a)*65,530+Math.sin(a)*45,82,prefs.motion?0:Math.sin(a)*.13);}
function draw(t,dt){ctx.clearRect(0,0,1200,900);if(bonusActive){drawBonus(t);return;}if(state==='menu'){drawMenu(t);return;}ctx.drawImage(images[LEVELS[level].bg],0,0,1200,900);if(level===0)bathroom(t);else if(level===1)gym(t);else if(level===2)palace(t);else sumoScene(t);drawHero(t);particles=particles.filter(p=>p.age<p.life);for(const p of particles){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.kind!=='steam')p.vy+=400*dt;drawParticle(p);}if(state==='finale')return;}
function tick(){if(!root.isConnected){stopMusic();stopEffects();return;}const t=now(),elapsedDt=Math.max(0,(t-lastFrame)/1000),dt=Math.min(.05,elapsedDt);lastFrame=t;if(!pauseReasons.size){tickExpansion(t);if(state==='countdown'){const a=t-countStart;if(a>=3000){state='playing';roundStart=t;announceCountdown('GO');button.disabled=false;button.focus({preventScroll:true});playMusic(LEVELS[level].music,true);setQuip(LEVELS[level].cause);}else announceCountdown(3-Math.floor(a/1000));}
if(state==='playing'){if(t-roundStart>=400)q('#countdown').hidden=true;if(holding&&runMode==='gentle'&&['pace','burst'].includes(sumoPhase(t).key)){holdAccumulator+=elapsedDt;while(holdAccumulator>=1/4.8&&state==='playing'){holdAccumulator-=1/4.8;tap(true);}}updateSumo(t);q('#award').hidden=t>=awardUntil;q('#time').textContent=(Math.max(0,DURATION-(t-roundStart))/1000).toFixed(1);if(t-roundStart>=DURATION)finish(t);}
sequence(t);if(state==='ending'){const a=t-endStart;if(a>=550&&events.plop===undefined){events.plop=t;q('#plop').hidden=false;fx('splash',.7);stopFx('gym-treadmill');if(level===1)fx('gym-bounce',.5);if(won)fx('voice-relief',.85);puff(570,700,-1,'water');puff(630,700,1,'water');setQuip(won?'SWEET, SWEET RELIEF!':'UNFINISHED BUSINESS…');}if(a>1800)q('#plop').hidden=true;if(a>[2200,2800,3200,3400][level])results(t);}
if(state==='done'){const u=clamp((t-events.tally)/2400);q('#result-score').textContent=Math.floor(scoreTotal*ease(u)).toLocaleString('en-GB');q('#next').disabled=u<1;if(u>=1){stopFx('tally');if(won&&level===LEVELS.length-1&&campaign.every(Boolean)&&t-events.tally>3200)beginFinale();}}
if(state==='finale')tickFinale(t);effects.forEach(e=>{if(e.stop&&t>=e.stop){e.audio.pause();e.stop=0;}});if(t-lastTap>110)button.classList.remove('hit');if(music)music.volume=.48*prefs.music*(prefs.effects>0&&t<voiceUntil?.80:1);}
if(state!=='loading')draw(t,dt);raf=requestAnimationFrame(tick);}
Promise.all(['bathroom','banana','gym','bodybuilder','palace','king','cast','props','deflated','lifter','runner','trainer','sumo','bathhouse'].map(name=>{const img=new Image();images[name]=img;img.src=ASSETS[name];return img.decode();})).then(()=>{q('#start').disabled=false;q('#start').textContent='START FLUSH';menu();lastFrame=now();raf=requestAnimationFrame(tick);}).catch(error=>{q('#start').textContent='ART FAILED TO LOAD';q('#menu-note').textContent='Please reload the game.';console.error(error);});
window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);stopMusic();stopEffects();});
if(window.__RF_TEST__)window.rfTest={get:()=>({state,level,taps,progress:progress(),events:{...events},campaign,unlocked,scoreTotal,perfectHits,runMode,muted,music:Object.entries(tracks).find(([,a])=>a===music)?.[0],effects:[...effects].map(([name,e])=>({name,playing:!e.audio.paused,stop:e.stop})),remaining:DURATION-(now()-roundStart),countdownLog:[...countdownLog],gym:{...gymMetrics},bonus:{active:bonusActive,score:bonusScore,hits:bonusHits,combo:bonusCombo,beat:bonusBeat(now()),elapsed:now()-bonusStart},sumo:{phase:sumoPhase(now()).key,cycle:sumoPhase(now()).cycle,good:sumoGood,pushCycle:sumoPushCycle,pushDown,pushEarned,held:pushStarted<0?0:now()-pushStarted},voiceUntil}),tap,choose:i=>{level=i;},start:()=>{bonusScore=0;campaign=LEVELS.map(()=>null);runMode=prefs.gentle?'gentle':'classic';startRound();},advance:n=>{taps=n;numbers();},finish:()=>{taps=LEVELS[level].target;finish(now());},menu,beginFinale,introBonus};
})();



