// Captain scene and the final, pointer/keyboard accessible lid bonus.
let lidsActive=false,lidScore=0,lidStart=0,lidEnd=0,lidNext=0,lidCombo=0,lidHits=0,lidMisses=0,lidSlots=[];
const LID_DURATION=35000;
function lidDifficulty(elapsed){const tier=Math.min(4,Math.floor(Math.max(0,elapsed)/7000));return {tier,max:tier+1,interval:[1050,800,600,450,300][tier],lifetime:[2400,2200,1900,1700,1500][tier],batch:tier>=3?2:1};}
const lidGrid=document.createElement('div');lidGrid.id='lid-grid';lidGrid.hidden=true;
q('#stage').append(lidGrid);
for(let i=0;i<6;i++){const b=document.createElement('button');b.className='lid-target';b.setAttribute('aria-label','Close toilet lid '+(i+1));b.textContent=String(i+1);b.onclick=()=>hitLid(i);lidGrid.append(b);}
function syncLids(){[...lidGrid.children].forEach((b,i)=>{b.disabled=state!=='lids-playing'||!lidSlots[i]?.open;b.setAttribute('aria-label','Toilet '+(i+1)+': '+(lidSlots[i]?.open?'open, close lid':'closed'));});}
function introLids(){q('#menu').hidden=true;q('#menu-deck').hidden=true;q('#hud').hidden=false;q('#chapter').hidden=false;q('#quip').hidden=false;cancelPush();stopMusic();stopEffects();bonusActive=scrubActive=false;lidsActive=true;state='lids-intro';lidScore=lidCombo=lidHits=lidMisses=0;lidSlots=Array.from({length:6},()=>({open:false,until:0,closed:-1e9}));lidGrid.hidden=true;q('#stage').className='stage lids-stage';q('#plop').hidden=true;q('#award').hidden=true;q('#countdown').hidden=true;q('#rhythm-guide').hidden=true;q('#controls').hidden=true;q('#result').hidden=false;q('#result-title').textContent='LID PANIC!';q('#result-eyebrow').textContent='FINAL BONUS · 35 SECONDS';q('#result-score').textContent='';q('#result-detail').textContent='Tap the OPEN toilet lids to slam them shut. They pop back up faster and faster! Keyboard: keys 1–6 match the toilets.';q('#best').textContent='CHAIN CLOSURES FOR BONUS POINTS · EVERY SCORE COUNTS';q('#next').textContent='BATTEN DOWN THE LIDS';q('#next').disabled=false;q('#chapter').textContent='★ LID PANIC';q('#level-number').textContent='BONUS 3';q('#time').textContent='35.0';q('#score').textContent='0';setQuip('SIX TOILETS. NO PEACE.');}
function startLids(){state='lids-countdown';countStart=now();countdownBeat=null;countdownLog=[];q('#result').hidden=true;lidGrid.hidden=false;syncLids();announceCountdown(3);const a=tracks.bonusMusic;a.muted=true;a.play().then(()=>{if(state==='lids-countdown'){a.pause();a.currentTime=0;}a.muted=muted;}).catch(()=>{a.muted=muted;});}
function hitLid(i){if(state!=='lids-playing'||pauseReasons.size)return;const t=now();if(t-lidStart>=LID_DURATION){endLids(t);return;}const s=lidSlots[i];if(!s?.open)return;if(t>=s.until){missLid(s);syncLids();return;}s.open=false;s.closed=t;lidHits++;lidCombo++;lidScore+=100+Math.min(lidCombo,10)*15;bonusSound('lid-close',.38);setQuip(lidCombo>=5?'LID LEGEND! STREAK ×'+lidCombo:'SLAM DUNK! STREAK ×'+lidCombo);q('#score').textContent=lidScore.toLocaleString('en-GB');syncLids();}
function missLid(s){s.open=false;lidCombo=0;lidMisses++;lidScore=Math.max(0,lidScore-25);setQuip('THAT ONE GOT AWAY! CATCH THE NEXT LID.');q('#score').textContent=lidScore.toLocaleString('en-GB');}
function endLids(t){if(state!=='lids-playing')return;state='lids-done';lidEnd=t;stopMusic();stopEffects(true);lidGrid.hidden=true;lidSlots.forEach(s=>s.open=false);fx('tally',.45,true,1800);q('#result').hidden=false;q('#result-title').textContent=lidHits?'BATTENED DOWN!':'BONUS BANKED!';q('#result-eyebrow').textContent='LID PANIC COMPLETE';q('#result-detail').textContent=lidHits+' lids shut · '+lidMisses+' escaped. Your bonus joins the final score.';q('#result-score').textContent='0';q('#next').textContent='FACE ZEUS';q('#next').disabled=true;q('#best').textContent='NEXT: THE THUNDER THRONE';}
function tickLids(t){if(state==='lids-countdown'){if(t-countStart>=3000){state='lids-playing';canvas.tabIndex=0;canvas.setAttribute('aria-label','Lid Panic: close open toilets using keys 1 to 6.');canvas.focus({preventScroll:true});lidStart=t;lidNext=t;announceCountdown('GO');playMusic('bonusMusic',true);}else announceCountdown(3-Math.floor((t-countStart)/1000));}
 if(state==='lids-playing'){const elapsed=t-lidStart;if(elapsed>=LID_DURATION){endLids(t);return;}if(elapsed>400)q('#countdown').hidden=true;for(const s of lidSlots)if(s.open&&t>=s.until)missLid(s);if(t>=lidNext){const eligible=lidSlots.map((s,i)=>!s.open&&t-s.closed>300?i:-1).filter(i=>i>=0);const difficulty=lidDifficulty(elapsed);let count=Math.min(difficulty.batch,difficulty.max-lidSlots.filter(s=>s.open).length,eligible.length);while(count-->0){const index=Math.floor(Math.random()*eligible.length),i=eligible.splice(index,1)[0];lidSlots[i].open=true;lidSlots[i].opened=t;lidSlots[i].until=t+difficulty.lifetime;}lidNext=t+difficulty.interval;}q('#time').textContent=((LID_DURATION-elapsed)/1000).toFixed(1);syncLids();}
 if(state==='lids-done'){const u=clamp((t-lidEnd)/1800);q('#result-score').textContent=Math.round(lidScore*ease(u)).toLocaleString('en-GB');q('#next').disabled=u<1;if(u>=1)stopFx('tally');}}
root.addEventListener('keydown',e=>{if(state==='lids-playing'&&!e.repeat&&!pauseReasons.size&&/^[1-6]$/.test(e.key)){e.preventDefault();hitLid(Number(e.key)-1);}});
function drawLids(t){ctx.drawImage(images.bathroom,0,0,1200,900);ctx.fillStyle='#04203aaa';ctx.fillRect(0,0,1200,900);for(let i=0;i<6;i++){const x=270+i%3*330,y=325+Math.floor(i/3)*330,s=lidSlots[i]||{};ctx.save();ctx.translate(x,y);roundRect(-95,-106,190,85,17,'#daf4fa');roundRect(-82,52,164,120,22,'#b9dae9');ctx.fillStyle='#fffde5';ctx.strokeStyle='#0b253d';ctx.lineWidth=8;ctx.beginPath();ctx.ellipse(0,18,112,77,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#23bddb';ctx.beginPath();ctx.ellipse(0,18,78,47,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=s.open?'#fff9ba':'#e6f7fd';ctx.beginPath();const opening=s.open?(prefs.motion?1:ease((t-s.opened)/150)):0;ctx.ellipse(0,12-95*opening,105,68+27*opening,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(s.open){text('!',0,-72,65);text((i+1)+' CLOSE!',0,33,25,'#fff44a');}else text(String(i+1),0,25,33,'#6fcddd');if(t-s.closed<260){text('SLAM!',0,-123,29);for(const side of [-1,1])line([[side*125,-30],[side*147,-55]],'#ffed52',7);}ctx.restore();}}
function drawShip(t){const p=progress(),plop=age('plop',t),sinking=won&&plop>=0,drop=sinking?ease(plop/3.4)*530:0,roll=prefs.motion?0:(signatureWave(t)-.5)*(.018+p*.028)+(sinking?clamp(plop/3)*.13:0);ctx.fillStyle='#80e8fa';ctx.fillRect(0,0,1200,900);ctx.fillStyle='#fffbe8';for(const [x,y]of [[130,90],[540,130],[1020,70]]){ctx.beginPath();ctx.ellipse(x,y,120,30,0,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#138ec6';ctx.fillRect(0,320,1200,580);for(let y=350;y<900;y+=65){line([[0,y],[240,y-5],[480,y],[720,y-5],[960,y],[1200,y-5]],'#72e6ef',4);}ctx.save();ctx.translate(600,450+drop-(state==='playing'&&!prefs.motion?signatureWave(t)*18:0));ctx.rotate(roll);ctx.drawImage(images['ship-foreground'],-650,-490,1300,980);ctx.translate(-600,-450);
 const frame=plop>=0?0:pushDown?pushEarned>8?2:1:p<.25?0:p<.7?1:2;const y=790+(prefs.motion?0:Math.sin(t/140)*p*3);if(!sinking||plop<1.8)sprite('captain',frame,600,y,620);
 if(p>.28){const sway=prefs.motion?0:Math.sin(t/120)*13;line([[190,665],[205,608],[245+sway,571]],'#092f4e',14);line([[190,665],[205,608],[245+sway,571]],'#6af4ff',8);}
 if(p>.52){const x=910-(prefs.motion?0:Math.sin(t/700)*65);ctx.save();ctx.translate(x,700);ctx.rotate(prefs.motion?0:t/850);roundRect(-39,-45,78,90,13,'#b76a2e');line([[-39,-23],[39,-23]],'#37465c',10);line([[-39,25],[39,25]],'#37465c',10);ctx.restore();}
 if(p>.75){for(const side of [-1,1])line([[600+side*90,765],[600+side*170,785],[600+side*145,824],[600+side*280,850]],'#18263a',7);}
 ctx.restore();const waterY=sinking?820-ease(plop/3)*245:875-(state==='playing'?signatureWave(t)*25:0);ctx.beginPath();ctx.moveTo(0,900);for(let x=0;x<=1200;x+=15)ctx.lineTo(x,waterY+Math.sin(x/75+(prefs.motion?0:t/300))*13);ctx.lineTo(1200,900);ctx.closePath();ctx.fillStyle='#119bddea';ctx.fill();ctx.strokeStyle='#aafaff';ctx.lineWidth=6;ctx.stroke();
 if(sinking&&plop>=1.8){ctx.save();ctx.beginPath();ctx.rect(380,0,440,waterY+22);ctx.clip();sprite('captain',0,600,waterY+125,430);ctx.restore();ctx.save();ctx.translate(600,waterY+20);ctx.strokeStyle='#ff7140';ctx.lineWidth=28;ctx.beginPath();ctx.ellipse(0,0,125,35,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#fffad5';ctx.lineWidth=16;for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(0,0,125,35,0,i*Math.PI/2,i*Math.PI/2+.25);ctx.stroke();}ctx.restore();text('CAPTAIN OVERBOARD!',600,180,38);}
 const flee=p>.65?(p-.65)*1600:0;for(let i=0;i<2;i++){const x=210+i*770+(i?-1:1)*flee,y=170-i*40-flee*.3,flap=prefs.motion?0:Math.sin(t/120+i)*12;line([[x-28,y-flap],[x,y],[x+28,y-flap]],'#fffce6',8);}if(state==='playing'&&p>.2&&t-lastSteam>230){lastSteam=t;puff(465,325,-1);puff(735,325,1);}if(t<signatureCelebrateUntil)for(const side of [-1,1]){line([[600+side*210,740],[600+side*275,675],[600+side*310,720]],'#9affff',9);}for(const particle of particles)drawParticle(particle);drawSignature(t);}
