// Only the gym and ship opt into these authored 35-second encounters.
let gymForm=4,gymWobbleUntil=0,signatureReleases=0,signatureLastInput=-1e9,nextGymForm=4,signatureCelebrateUntil=0,signatureScoreBonus=0;
function resetSignature(){signatureScoreBonus=0;nextGymForm=4;signatureCelebrateUntil=0;gymForm=4;gymWobbleUntil=0;signatureReleases=0;signatureLastInput=-1e9;}
function signaturePhase(t){if(level===6)return zeusPhase(t);const elapsed=Math.max(0,t-roundStart),cycle=Math.min(2,Math.floor(elapsed/11500)),local=elapsed-cycle*11500;
 const gym=level===1,rows=gym?[
 ['burst',[2300,2200,2100][cycle],'REPS!','QUICK TAPS · ABOUT FOUR A SECOND','faster'],
 ['ready',1200,'BRACE…','FINGER OFF · PREPARE YOUR BIG LIFT','get-ready'],
 ['hold',[3800,4200,4600][cycle],'LIFT & HOLD','KEEP PRESSED UNTIL RELEASE','push-hold'],
 ['release',[1400,1100,900][cycle],'RACK IT!','RELEASE NOW · GOOD FORM EARNS EXTRA','release'],
 ['pace',[2800,2800,2700][cycle],'RECOVER','SLOW TAPS · TWO A SECOND · KEEP GOOD FORM','pace-it']
 ]:[
 ['pace',2500,'SWELL APPROACHING','SLOW TAPS · WATCH THE WAVE','pace-it'],
 ['ready',1000,'BRACE FOR THE CLIMB','FINGER OFF · HOLD IS NEXT','get-ready'],
 ['hold',[4400,4600,4800][cycle],'RIDE UP · HOLD','KEEP PRESSED UNTIL THE CREST TURNS GREEN','push-hold'],
 ['release',[1300,1100,900][cycle],'CREST! RELEASE!','LET GO WHILE THE CREST IS GREEN','release'],
 ['burst',2300,'SURF DOWN!','FAST TAPS · ABOUT FOUR A SECOND','faster']
 ];let begin=0;for(let i=0;i<rows.length;i++){const [key,duration,title,detail,voice]=rows[i];if(local<begin+duration||i===rows.length-1)return {key,cycle,duration,begin:cycle*11500+begin,fraction:clamp((local-begin)/duration),left:Math.max(0,begin+duration-local),title:(gym?'SET ':'WAVE ')+(cycle+1)+'/3 · '+title,detail,voice,word:key==='pace'?'SLOW':key==='burst'?'FAST':key==='hold'?'HOLD':key==='release'?'RELEASE':'READY',color:key==='release'?'#bbff64':key==='hold'?'#ffcc68':'#76efff'};begin+=duration;}}
function signatureWave(t){const p=signaturePhase(t);return p.key==='hold'?ease(p.fraction):p.key==='release'?1:p.key==='burst'?1-ease(p.fraction):0;}
function releaseSignature(cancel){if(!pushDown)return;const t=now(),phase=signaturePhase(t),held=t-pushStarted;stopFx('meter-hold');pushDown=false;pushStarted=-1;if(cancel||pauseReasons.size||state!=='playing')return;
 if(phase.key==='release'&&held>=1500&&sumoPushCycle!==phase.cycle){sumoPushCycle=phase.cycle;perfectHits++;signatureReleases++;if(level===1&&pushEarned<12.8)gymForm=Math.min(gymForm,2);const gain=level===1?8+gymForm:15;signatureScoreBonus+=level===1?gymForm*15:75;signatureCelebrateUntil=t+1400;addSignatureRelief(gain,t);sumoFeedback=level===1?(gymForm===4?'PERFECT SET!':'SET RACKED!')+' +'+gain+' · SKILL +'+(gymForm*15)+' POINTS':level===6?'GODLIKE! +75 SKILL POINTS':'PERFECT CREST! +75 POINTS · SURF DOWN!';fx('meter-release',.4);puff(400,740,-1);puff(800,740,1);}else{sumoFeedback=phase.key==='hold'?'TOO EARLY! HOLD UNTIL THE GREEN RELEASE CUE.':'MISSED IT! THE NEXT ONE IS COMING.';if(level===1){gymWobbleUntil=t+900;gymForm=Math.max(0,gymForm-2);}}sumoFeedbackUntil=t+1100;}
function updateSignature(t){const phase=signaturePhase(t);if(pushCycle!==phase.cycle){cancelPush();pushCycle=phase.cycle;pushEarned=0;keepSaid=false;gymForm=nextGymForm;nextGymForm=4;}
 const cap=level===1?16:22;if(pushDown&&phase.key==='hold'){const amount=Math.min(cap-pushEarned,Math.max(0,t-pushLastTick)/phase.duration*cap);pushEarned+=amount;if(amount>0)addSignatureRelief(amount,t);}pushLastTick=t;if(state!=='playing')return;
 rhythmGuide(phase.title,phase.key==='hold'?(pushDown?'KEEP HOLDING · '+Math.round(pushEarned/cap*100)+'% CHARGE':phase.detail):phase.detail,phase.key==='hold'?pushEarned/cap:phase.fraction,phase.color);q('#rhythm-guide').hidden=false;
 const key=phase.cycle+phase.key;if(key!==sumoLastPhase&&t-roundStart>=voiceLengths.go&&t>=voiceUntil){sumoLastPhase=key;if(phase.key==='release'||phase.left>=voiceLengths[phase.voice])fx('voice-'+phase.voice,.85);q('#status').textContent=phase.title+'. '+phase.detail;}
 q('#flush-word').textContent=phase.word;q('#flush-hint').textContent=phase.key==='hold'?'KEEP PRESSED':phase.key==='release'?'LET GO NOW':phase.key==='ready'?'FINGER OFF':phase.key==='pace'?'STEADY TAPS':'QUICK TAPS';button.classList.toggle('ready',phase.key==='release');button.classList.toggle('charging',phase.key==='hold'||phase.key==='ready');button.classList.toggle('pushing',pushDown);
 setQuip(t<sumoFeedbackUntil?sumoFeedback:level===6?(phase.key==='hold'?'CONTAIN THE POWER! WAIT FOR GREEN!':phase.key==='release'?'UNLEASH THE THUNDER!':LEVELS[6].lines[Math.min(3,Math.floor(progress()*4))]):level===1?(phase.key==='pace'?'RECOVER, BIG GUY! SAVE SOME FOR THE NEXT SET.':phase.key==='hold'?'THAT’S IT! HOLD THE BIGGEST REP OF YOUR LIFE!':'THREE SETS. ONE VERY BRAVE TOILET.'):(phase.key==='release'?'GREEN CREST! LET GO, CAPTAIN!':phase.key==='burst'?'SURF IT HOME! ALL HANDS TAPPING!':'WORK WITH THE WAVES, CAPTAIN!'));}
function tapSignature(t,auto){const phase=signaturePhase(t),gap=t-sumoGood,inputGap=t-signatureLastInput;signatureLastInput=t;if(!auto)manualTaps++;lastTap=t;let gain=0;
 if(phase.key==='pace'&&gap>=(level===1?400:420))gain=level===1?2.1:2.8;if(phase.key==='burst'&&gap>=180)gain=level===1?2.1:2.1;
 if(level===1&&!auto&&((phase.key==='pace'&&inputGap<350)||(phase.key==='burst'&&inputGap<130))){if(phase.key==='pace')nextGymForm=Math.max(0,nextGymForm-1);else gymForm=Math.max(0,gymForm-1);gymWobbleUntil=t+700;sumoFeedback='EASY! MUSCLES WOBBLING · PROTECT YOUR FORM BONUS.';sumoFeedbackUntil=t+900;}
 if(gain){sumoGood=t;button.classList.add('hit');fx('meter-tap',.2);addSignatureRelief(gain,t);}else if(t>=sumoFeedbackUntil){sumoFeedback=phase.key==='pace'?'SLOW AND STEADY!':phase.key==='hold'?'KEEP THE BUTTON HELD DOWN!':'WATCH THE CUE · YOUR MOMENT IS COMING!';sumoFeedbackUntil=t+700;}numbers();}
function drawSignature(t){if(!['playing','countdown'].includes(state))return;if(t<signatureCelebrateUntil)text(level===1?(gymForm===4?'PERFECT SET!':'GOOD LIFT!'):'CREST MASTER!',600,155,38,'#baff62');const phase=signaturePhase(t);roundRect(65,230,245,112,12,'#0b244bea','#75e8ed',3);text((level===1?'SET ':'WAVE ')+(phase.cycle+1)+' / 3',187,258,23);
 if(level===1){text((phase.key==='pace'?'NEXT FORM +':'FORM BONUS +')+(phase.key==='pace'?nextGymForm:gymForm),187,287,18,'#bbff64');text(signatureReleases+' SETS RACKED',187,318,16,'#aafaff');}else{const x=86+signatureWave(t)*195;line([[86,320],[130,312],[190,288],[240,281],[281,281]],'#70dfff',5);line([[244,281],[281,281]],phase.key==='release'?'#baff51':'#ffc351',10);ctx.fillStyle=phase.key==='release'?'#baff51':'#fff7bc';ctx.beginPath();ctx.arc(x,320-signatureWave(t)*39,10,0,Math.PI*2);ctx.fill();text(phase.key==='release'?'RELEASE!':'WATCH THE CREST',187,278,14,'#fff9b5');}}

function addSignatureRelief(gain,t){const phase=signaturePhase(t);if(phase.cycle<2||!['release','pace','burst'].includes(phase.key)||phase.cycle===2&&(level===1&&phase.key==='burst'||level===6&&phase.key!=='release'))gain=Math.min(gain,Math.max(0,LEVELS[level].target-1-taps));addSumoRelief(gain,t);}
