// Scrub bonus uses the same paused game clock and audio mixer as the main rounds.
let scrubActive=false,scrubScore=0,scrubStart=0,scrubEnd=0,scrubStains=[],scrubPointer=null,
    brush={x:600,y:480},scrubPrevious=null,scrubLastMove=0,scrubCombo=0,scrubLastClean=-1e9,
    scrubSparkles=[],scrubKeys=new Set(),scrubLastTick=0,scrubTimeBonus=0,spaceVent=-1e9;
let scrubSound=null;
function quietScrub(){if(scrubSound)stopFx(scrubSound);scrubSound=null;}
const stainPositions=[[440,285],[610,240],[770,315],[820,485],[730,660],[500,680],[375,495]];
function cleanFraction(){return scrubStains.length?scrubStains.reduce((a,s)=>a+1-s.dirt/s.total,0)/scrubStains.length:0;}
function stopScrubInput(){quietScrub();scrubPointer=null;scrubPrevious=null;scrubKeys.clear();}
function introScrub(){cancelPush();stopMusic();stopEffects();bonusActive=false;scrubActive=true;state='scrub-intro';q('#stage').className='stage scrub-stage';scrubScore=0;scrubCombo=0;scrubTimeBonus=0;scrubSparkles=[];scrubLastClean=-1e9;stopScrubInput();brush={x:600,y:480};scrubStains=stainPositions.map(([x,y],i)=>({x,y,tier:i%3,total:[110,210,330][i%3],dirt:[110,210,330][i%3],done:false}));q('#plop').hidden=true;q('#award').hidden=true;q('#countdown').hidden=true;q('#rhythm-guide').hidden=true;q('#result').hidden=false;q('#controls').hidden=true;q('#chapter').textContent='★ SCRUB CLUB';q('#level-number').textContent='BONUS 2';q('#time').textContent='12.0';q('#score').textContent='0';q('#result-title').textContent='SCRUB CLUB!';q('#result-eyebrow').textContent='BONUS ROUND · 12 SECONDS';q('#result-score').textContent='';q('#result-detail').textContent='Drag the brush back and forth over every splat. Light stains wipe off quickly; darker crusts need more scrubbing and earn more points. Quick clean-ups build a combo. Keyboard: hold Space and move with the arrow keys.';q('#best').textContent='CLEAN EARLY FOR EXTRA POINTS · YOU ALWAYS CONTINUE';q('#next').textContent='GRAB THE BRUSH';q('#next').disabled=false;setQuip('THE SUMO HAS LEFT YOU A LITTLE PRESENT…');canvas.tabIndex=0;canvas.setAttribute('aria-label','Scrub Club: drag over stains, or hold Space and move with arrow keys.');}
function startScrub(){state='scrub-countdown';countStart=now();countdownBeat=null;countdownLog=[];q('#result').hidden=true;q('#controls').hidden=false;button.disabled=true;q('#flush-word').textContent='SCRUB';q('#flush-hint').textContent='DRAG THE BRUSH';q('#fill').style.width='0%';q('#percent').textContent='0%';q('#taps-label').textContent='0 / 7 CLEAN';q('.meter').setAttribute('aria-valuenow','0');announceCountdown(3);const a=tracks.bonusMusic;a.muted=true;a.play().then(()=>{if(state==='scrub-countdown'){a.pause();a.currentTime=0;}a.muted=muted;}).catch(()=>{a.muted=muted;});}
function scrubAt(x,y){if(state!=='scrub-playing'||pauseReasons.size)return;const t=now();if(t-scrubStart>=12000){endScrub(t);return;}const next={x:clamp(x,260,940),y:clamp(y,155,775)};if(!scrubPrevious){brush=next;scrubPrevious={...next};scrubLastMove=t;return;}const previous=scrubPrevious,dx=next.x-previous.x,dy=next.y-previous.y,distance=Math.hypot(dx,dy),dt=Math.max(0,t-scrubLastMove);brush=next;scrubPrevious={...next};scrubLastMove=t;if(distance<1||dt<=0)return;
  // Integrate along the stroke, capped by elapsed time: teleports cannot clear a bowl.
  const steps=Math.max(1,Math.ceil(distance/12)),effort=Math.min(distance,dt*1.7)/steps;
  let touched=false;for(let j=1;j<=steps;j++){const px=previous.x+dx*j/steps,py=previous.y+dy*j/steps;for(const stain of scrubStains){if(stain.done||Math.hypot(stain.x-px,stain.y-py)>66)continue;touched=true;stain.dirt=Math.max(0,stain.dirt-effort);if(stain.dirt===0){stain.done=true;scrubCombo=t-scrubLastClean<1800?scrubCombo+1:1;scrubLastClean=t;scrubScore+=[120,220,340][stain.tier]+Math.min(scrubCombo,5)*40;scrubSparkles.push({x:stain.x,y:stain.y,at:t});fx('meter-tap',.3);setQuip('SQUEAKY CLEAN! COMBO ×'+scrubCombo);q('#status').textContent='Stain cleaned. Combo '+scrubCombo;}}}
  if(touched){if(!scrubSound||effects.get(scrubSound)?.audio.paused){scrubSound='scrub-'+(1+Math.floor(Math.random()*4));fx(scrubSound,.3,true,150);}const sound=effects.get(scrubSound);if(sound)sound.stop=t+150;}else quietScrub();
  const percent=Math.round(cleanFraction()*100);q('#percent').textContent=percent+'%';q('#fill').style.width=percent+'%';q('.meter').setAttribute('aria-valuenow',String(percent));q('#score').textContent=scrubScore.toLocaleString('en-GB');q('#taps-label').textContent=scrubStains.filter(s=>s.done).length+' / 7 CLEAN';if(scrubStains.every(s=>s.done)){scrubTimeBonus=Math.floor((12000-(t-scrubStart))/100)*10;scrubScore+=scrubTimeBonus;endScrub(t);}}
function endScrub(t){if(state!=='scrub-playing')return;state='scrub-ending';scrubEnd=t;stopScrubInput();stopMusic();stopEffects();fx('splash',.35);setQuip(cleanFraction()===1?'PORCELAIN PERFECTION!':'GOOD SCRUBBING! YOUR BONUS IS BANKED.');q('#score').textContent=scrubScore.toLocaleString('en-GB');}
function tickScrub(t){if(state==='scrub-countdown'){if(t-countStart>=3000){state='scrub-playing';scrubStart=scrubLastTick=t;announceCountdown('GO');canvas.focus({preventScroll:true});playMusic('bonusMusic',true);}else announceCountdown(3-Math.floor((t-countStart)/1000));}
  if(state==='scrub-playing'){const dt=Math.min(50,t-scrubLastTick);scrubLastTick=t;if(t-scrubStart>400)q('#countdown').hidden=true;let dx=(scrubKeys.has('ArrowRight')?1:0)-(scrubKeys.has('ArrowLeft')?1:0),dy=(scrubKeys.has('ArrowDown')?1:0)-(scrubKeys.has('ArrowUp')?1:0);if(dx||dy){const len=Math.hypot(dx,dy);if(scrubKeys.has('Space'))scrubAt(brush.x+dx/len*dt*.65,brush.y+dy/len*dt*.65);else{brush.x=clamp(brush.x+dx/len*dt*.65,260,940);brush.y=clamp(brush.y+dy/len*dt*.65,155,775);scrubPrevious=null;}}if(t-scrubLastClean>1400)setQuip('BACK AND FORTH! GIVE THAT LAST PATCH SOME ELBOW GREASE!');q('#time').textContent=(Math.max(0,12000-(t-scrubStart))/1000).toFixed(1);if(t-scrubStart>=12000)endScrub(t);}
  if(state==='scrub-ending'&&t-scrubEnd>=1500){state='scrub-done';events.tally=t;fx('tally',.45,true,1800);q('#result').hidden=false;q('#result-title').textContent=cleanFraction()===1?'PORCELAIN PERFECTION!':'BONUS BANKED!';q('#result-eyebrow').textContent='SCRUB CLUB COMPLETE';q('#result-detail').textContent=scrubStains.filter(s=>s.done).length+' of 7 stains cleared. '+(scrubTimeBonus?'Plus '+scrubTimeBonus+' time bonus!':'Your points join the campaign total.');q('#best').textContent='NEXT STOP: ORBIT';q('#next').textContent='ON TO LEVEL 5';q('#next').disabled=true;}
  if(state==='scrub-done'){const u=clamp((t-events.tally)/1800);q('#result-score').textContent=Math.round(scrubScore*ease(u)).toLocaleString('en-GB');q('#next').disabled=u<1;if(u>=1)stopFx('tally');}}
function brushPoint(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*1200,y:(e.clientY-r.top)/r.height*900};}
canvas.addEventListener('pointerdown',e=>{if(state!=='scrub-playing'||pauseReasons.size||e.button!==0||scrubPointer!==null)return;e.preventDefault();canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);scrubPointer=e.pointerId;const p=brushPoint(e);scrubAt(p.x,p.y);});
canvas.addEventListener('pointermove',e=>{if(e.pointerId!==scrubPointer)return;const p=brushPoint(e);scrubAt(p.x,p.y);});
for(const ev of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(ev,e=>{if(e.pointerId===scrubPointer)stopScrubInput();});
root.addEventListener('keydown',e=>{if(state==='scrub-playing'&&!pauseReasons.size&&['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();scrubKeys.add(e.code);}});root.addEventListener('keyup',e=>{scrubKeys.delete(e.code);if(e.code==='Space'){scrubPrevious=null;quietScrub();}});window.addEventListener('blur',stopScrubInput);
function drawScrub(t){ctx.drawImage(images.bathroom,0,0,1200,900);ctx.fillStyle='#03162bb8';ctx.fillRect(0,0,1200,900);ctx.save();ctx.translate(600,465);ctx.fillStyle='#bacfd9';ctx.strokeStyle='#0a1b31';ctx.lineWidth=12;ctx.beginPath();ctx.ellipse(0,0,345,375,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fffdeb';ctx.beginPath();ctx.ellipse(0,-7,315,345,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#d7f3ee';ctx.beginPath();ctx.ellipse(0,10,247,285,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#49daea';ctx.beginPath();ctx.ellipse(0,105,147,143,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#b9ffff';ctx.lineWidth=6;ctx.beginPath();ctx.ellipse(0,100,98,90,0,0,Math.PI*2);ctx.stroke();ctx.restore();
  scrubStains.forEach((s,i)=>{if(s.done)return;ctx.save();ctx.translate(s.x,s.y);const size=.45+.55*s.dirt/s.total;ctx.scale(size,size);ctx.fillStyle=['#bd8142','#965122','#65351d'][s.tier];ctx.strokeStyle='#58311b';ctx.lineWidth=4;ctx.beginPath();for(let n=0;n<=32;n++){const a=n/32*Math.PI*2,r=37+Math.sin(a*5+i)*9;n?ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r*.8):ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r*.8);}ctx.fill();ctx.stroke();if(s.tier){ctx.strokeStyle='#d99c60';ctx.lineWidth=3;for(let k=0;k<Math.ceil(s.dirt/s.total*(s.tier+2));k++){const x=-24+k*16;line([[x,-16],[x+8,0],[x-3,16]],'#d99c60',3);}}ctx.restore();});
  for(const s of scrubSparkles){const a=(t-s.at)/1000;if(a>1.3)continue;for(let i=0;i<5;i++){const angle=i*Math.PI*2/5,x=s.x+Math.cos(angle)*a*70,y=s.y+Math.sin(angle)*a*70;ctx.globalAlpha=1-a/1.3;line([[x-8,y],[x+8,y]],'#fffd9b',4);line([[x,y-8],[x,y+8]],'#fffd9b',4);}ctx.globalAlpha=1;}
  if(state==='scrub-playing'||state==='scrub-countdown'){ctx.save();ctx.translate(brush.x,brush.y);ctx.rotate(-.5);roundRect(-12,-150,24,160,10,'#f9a63d');ctx.fillStyle='#f4faff';ctx.strokeStyle='#163557';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,8,43,52,0,0,Math.PI*2);ctx.fill();ctx.stroke();for(let i=-25;i<=25;i+=10)line([[i,-24],[i,44]],'#7cbdd3',3);ctx.restore();}if(state==='scrub-ending'&&cleanFraction()===1)text('SPARKLING!',600,430,64,'#fff875');}
function spaceScene(t){const p=progress(),plop=age('plop',t);if(p>.93&&events.spaceStill===undefined)events.spaceStill=t;const freeze=plop<0&&p>.93,anim=prefs.motion?0:(freeze?events.spaceStill:t),orbit=plop>=0?events.plop/1600-plop*(1+p*2):anim/1600;
  ctx.save();ctx.beginPath();ctx.ellipse(930,202,172,171,0,0,Math.PI*2);ctx.clip();const drift=prefs.motion?0:Math.sin(t/5000)*5;ctx.drawImage(images.space,0,0,images.space.width,images.space.height,drift,0,1200,900);const frame=plop>=0?2:p<.5?0:p<.75?1:2;sprite('alien',frame,940+(plop>=0?Math.min(plop,3)*120:Math.sin(anim/1000)*10),345-(plop>=0?plop*95:0),250,plop>=0&&!prefs.motion?plop*4:0);ctx.restore();
  for(let i=0;i<3;i++){const side=i===1?1:-1,x=600+side*(330+Math.cos(orbit+i*2)*60),y=310+i*150+Math.sin(orbit+i)*70;ctx.save();ctx.translate(x,y);ctx.rotate(prefs.motion?0:orbit+i);if(i===0){roundRect(-7,-50,14,100,4,'#ffd13c');line([[0,-42],[0,-20]],'#fafbff',5);}else if(i===1){roundRect(-34,-42,68,84,8,'#fb9951');text('CHEESE',0,4,14,'#fff2a3');}else{roundRect(-33,-30,66,60,8,'#fff8db');ctx.fillStyle='#8b6641';ctx.beginPath();ctx.ellipse(0,0,10,22,0,0,Math.PI*2);ctx.fill();if(p>.25){const pts=[];for(let j=0;j<12;j++)pts.push([30+j*10,15+Math.sin(j*.8+orbit)*13]);line(pts,'#f4f3da',13);}}ctx.restore();}
  if(p>.75){ctx.save();ctx.globalAlpha=prefs.motion?.3:.15+.15*(1+Math.sin(t/240));ctx.fillStyle='#ff3b31';ctx.beginPath();ctx.arc(260,97,40,0,Math.PI*2);ctx.fill();ctx.restore();}
  roundRect(67,235,222,71,12,'#102c53','#6befff',3);text('SUIT PRESSURE',178,257,17,'#a1faff');roundRect(86,270,180,16,6,'#071529',null,0);roundRect(86,270,Math.max(2,pushEarned/14*180),16,6,pushDown?'#ffcf50':'#55e5dd',null,0);
  if(plop>=0&&plop<1.2){ctx.save();ctx.globalAlpha=1-plop/1.2;ctx.strokeStyle='#a9faff';ctx.lineWidth=12;ctx.beginPath();ctx.ellipse(600,620,plop*800,plop*500,0,0,Math.PI*2);ctx.stroke();ctx.restore();}}
function drawAstronaut(t){const p=progress(),plop=age('plop',t),lift=plop>=0?ease(plop/1.2)*65:0,frame=plop>=0?0:pushDown?pushEarned>8?2:1:p<.25?0:p<.65?1:2,r=RECTS.astronaut[frame],h=610,w=h*r[2]/r[3],motion=prefs.motion?0:1;for(let sy=0;sy<r[3];sy+=8){const sh=Math.min(8,r[3]-sy),v=sy/r[3],v2=(sy+sh)/r[3],dy=z=>168+z*h-lift*Math.pow(1-z,1.5)+Math.sin(z*Math.PI)*Math.sin(t/220)*p*3*motion;ctx.drawImage(images.astronaut,r[0],r[1]+sy,r[2],sh,600-w/2,dy(v),w,dy(v2)-dy(v)+.5);}
  if(plop>=0)for(const side of [-1,1])line([[600+side*135,560-lift*.35],[600+side*200,775]],'#394354',9);
  const vent=t-spaceVent<950||plop>=0&&plop<1.2;if(vent){for(const side of [-1,1]){ctx.fillStyle='#55e8ff';ctx.strokeStyle='#ddffff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(600+side*166,317-lift*.7);ctx.lineTo(600+side*(220+(prefs.motion?0:Math.sin(t/40)*15)),307-lift*.7);ctx.lineTo(600+side*166,332-lift*.7);ctx.closePath();ctx.fill();ctx.stroke();}}
  if(state==='playing'&&p>.25&&t-lastSteam>500){lastSteam=t;puff(450,355,-1,'sweat');puff(750,355,1,'sweat');}}

